import './globals.css';

import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Providers } from '@/components/providers';
import { SaaSMakerFeedback } from '@/components/saasmaker-feedback';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const SITE_URL = 'https://starboard.codevetter.com';
const SITE_DESCRIPTION =
  'Connect a public GitHub project, find similar repositories, and trace suggested tools to the peers that actually use them.';

export const metadata: Metadata = {
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icon.svg', type: 'image/svg+xml' },
    ],
    apple: '/apple-touch-icon.png',
  },

  metadataBase: new URL(SITE_URL),
  title: {
    default: 'Starboard — Tool intelligence for GitHub projects',
    template: '%s — Starboard',
  },
  description: SITE_DESCRIPTION,
  applicationName: 'Starboard',
  keywords: [
    'GitHub projects',
    'developer tools',
    'repository intelligence',
    'open source discovery',
  ],
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: 'Starboard',
    title: 'Starboard — Tool intelligence for GitHub projects',
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Starboard — Tool intelligence for GitHub projects',
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: fleet-generated JSON-LD
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://sassmaker.com/#org","name":"SaaS Maker (Foundry)","url":"https://sassmaker.com","sameAs":["https://sassmaker.com","https://github.com/Codevetter/starboard"]},{"@type":"SoftwareApplication","@id":"https://starboard.codevetter.com/#app","name":"Starboard","url":"https://starboard.codevetter.com","description":"GitHub stars organizer with semantic search — sub-product of CodeVetter for repo intelligence.","publisher":{"@id":"https://sassmaker.com/#org"}}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
        <script
          id="starboard-name-shim"
          dangerouslySetInnerHTML={{
            __html: 'globalThis.__name=globalThis.__name||function(t){return t};',
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}
          <SaaSMakerFeedback />
        </Providers>
      </body>
    </html>
  );
}
