import './globals.css';

import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Providers } from '@/components/providers';
import { SaaSMakerFeedback } from '@/components/saasmaker-feedback';
import { VitalsReporter } from '@/components/VitalsReporter';
import { auth } from '@/lib/auth';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const SITE_URL = 'https://starboard.codevetter.com';
const SITE_DESCRIPTION =
  'Connect a public GitHub project, understand its tool context, and discover better open-source projects with explained recommendations.';

export const metadata: Metadata = {
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icon.svg', type: 'image/svg+xml' },
    ],
    apple: '/apple-touch-icon.png',
  },

  metadataBase: new URL(SITE_URL),
  title: {
    default: 'Starboard — Tool intelligence for GitHub projects',
    template: '%s — Starboard',
  },
  description: SITE_DESCRIPTION,
  applicationName: 'Starboard',
  keywords: [
    'GitHub projects',
    'developer tools',
    'repository intelligence',
    'open source discovery',
  ],
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: 'Starboard',
    title: 'Starboard — Tool intelligence for GitHub projects',
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Starboard — Tool intelligence for GitHub projects',
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Hydrate SessionProvider from the server so post-login pages do not block
  // on a slow client /api/auth/session round-trip (observed ~17s cold).
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Person","@id":"https://sarthakagrawal.dev/#person","name":"Sarthak Agrawal","jobTitle":"AI Infrastructure & Product Engineer","url":"https://sarthakagrawal.dev","image":"https://avatars.githubusercontent.com/u/43884471?v=4","sameAs":["https://sarthakagrawal.dev","https://www.linkedin.com/in/sarthakagrawal927","https://github.com/sarthakagrawal927","https://x.com/sarthakcodes","https://huggingface.co/sarthakagrawal927"],"knowsAbout":["AI infrastructure","Local-first software","Post-training language models","AI code review","Cloudflare Workers","TypeScript","Rust"],"affiliation":{"@type":"Organization","@id":"https://sassmaker.com/#app","name":"SaaS Maker","url":"https://sassmaker.com"}},{"@type":"SoftwareApplication","@id":"https://starboard.codevetter.com/#app","name":"CodeVetter","alternateName":["Code Vetter","codevetter.com"],"url":"https://starboard.codevetter.com","description":"GitHub stars organizer with semantic search — sub-product of CodeVetter for repo intelligence.","publisher":{"@id":"https://sarthakagrawal.dev/#person"},"sameAs":["https://github.com/Codevetter/starboard"]}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
        <script
          id="starboard-name-shim"
          dangerouslySetInnerHTML={{
            __html: 'globalThis.__name=globalThis.__name||function(t){return t};',
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers session={session}>
          {children}
          <SaaSMakerFeedback />
          <VitalsReporter />
        </Providers>
      </body>
    </html>
  );
}
