// Generated by landing-astro/scripts/sync-articles.mjs — do not hand-edit.
export const PUBLISHED_ARTICLE_SLUGS: readonly string[] = [
  'a-due-diligence-checklist-for-evaluating-a-github-repository',
  'confidence-and-provenance-in-automated-tool-detection',
  'designing-public-repository-discovery-before-sign-in',
  'detecting-tools-from-manifests-without-overstating-certainty',
  'how-project-context-improves-open-source-recommendations',
  'how-semantic-search-changes-repository-discovery',
  'how-to-compare-github-repositories-beyond-stars-and-forks',
  'how-to-make-open-source-tool-recommendations-explainable',
  'popularity-vs-relevance-when-choosing-an-open-source-dependency',
  'turning-github-stars-into-a-useful-personal-technical-library',
  'using-similar-repositories-as-evidence-for-tool-recommendations',
  'what-an-sbom-can-reveal-about-a-repository-s-tools',
  'why-connected-project-discovery-should-request-minimal-github-permissions',
];
